development:  
  # 配置图片的域名
  upload_url: "http://static.1trip.me"
  # 上传途径
  upload_path: "/Users/chucklee/Developments/Web/UploadFiles/OneTripWeb"
  
test:  
  # 配置图片的域名
  upload_url: "http://127.0.0.1:3000/uploads"
  # 上传途径
  upload_path: "/home/boli/work/ChuckLee-Blog/public/uploads"
  
production:  
  # 配置图片的域名
  upload_url: "http://www3.chinabeibao.com/uploads"
  # 上传途径
  upload_path: "/wwwroot/chinabeibao/site/public/uploads"